export default {
    "Contact":[
        {
            id:1,
            Header:'Contact',
            para:'OrientedGrowth provide value to individuals life, where that is health, \
            mind and body and soul. Article provided on the website \
            is from authors experience and ventures.'
        }

    ],
    "About":[
{       
        id: 1,
        AboutHeader: 'ABOUT US',
        AboutPara: ' Oriented Growth is a free to use website where many are \
                    welcome to share experiences about growing as a person in the world. \
                    In a day and age where young adults get lost in doing what is best for themselves,\
                    We strive to deliver articles that live a healthy lifestyle.'
},
{       
        id: 2,
        MissionHeader: 'OUR MISSION',
        MissionPara: 'We plan to be the most leading web platform to acknowledge self-growth.\
                     From many different life experiences around the world, \
                     we hope to share and motivate young adults to live a Meaningful Life.'
}],

"Articles":[

    {
        id: 1,
        article1: 1,
        title:"WAYS TO MITIGATE DISCIPLINE",
        img: "/images/image7.png",
        name:"",
        date:"Last Updated Dec. 6, 2022",
        subTitle1:"Lower the usage of Social media",
        text1: "In today's modern world, Social media is everywhere: on your phone, smartwatch, and even on your refrigerator. The average usage of social media is two hours every day. As technology advances, more useless information also increases. Migrating what information you intake is vital to your self-growth. Reflect on what you did on social media apps by the end of the day and conclude with yourself to see if any information you intake benefits you. Track your time every day on different social media apps. Lower that time of day and find which content you need to improve self-growth.",
        subTitle2:"Start going to the gym.",
        text2: "The number of people that started going to the gym today compared to 10 years ago has been a considerable jump. Many do it for the likes and comments, and very few do it to develop themselves. One thing the gym has done to many is have a strict routine. Not only does the gym boost your discipline, but it's also good for your body and mind. After a gym session, you will be relieved of the majority of stress and increase your brain health, making you prone to less disease and decreasing your blood pressure genes living longer.",
        subTitle3:"Building a routine",
        text3: "Building a routine is one of the best ways to develop your discipline. A regime allows you to stick to a set of rhymes.Sticking to the verses will let you complete what needs to be done, regardless of how you feel. An average day will feel more prioritized, and you will focus more on your objective and know what to do.Think about what you're doing.",
        subTitle4:"Think about what you're doing",
        text4: "When you are doing anything, think about what you are doing. Losing focus on what matters at that moment can play a huge factor in your discipline. When you are feeling lazy, you will know that feeling and what action you need to take. You can use willpower to power through and do what needs to get done.",
        subTitle5:"Set goals",
        text5: "Setting a goal is the most important thing you can do for yourself. A goal keeps you on track with your main objective. It allows you to focus and reminds you of whatever you are doing to keep doing it. At the same time, it will save you discipline and encourage productivity by the day.",
        subTitle6:"Reward yourself for every accomplishment",
        text6: "Finally, reward yourself. Constantly working and being productive every day is a challenging task. However, enjoying the journey will even motivate you to do better. So as long you remember your objective and your goals. Know your limit understand yourself, and have clarity on what you are doing. Whatever action you do, you are always in control; having that controlling ability will set you far apart from others.",
        
    },
    {
        id: 2,
        article1: 2,
        title:"BEST WAY TO PRACTICE RESILIENCE",
        img: "/images/image4.png",
        name:"",
        date:"Last Updated Dec. 2, 2022",
        text0:"Resilience is an incredibly valuable skill, one that's not just about surviving the rough patches.",
        subTitle1:"Acknowledge and Understand Resilience",
        text1:"First things first, resilience isn't a trait that people either have or don't have. It involves behaviors, thoughts, and actions that anyone can learn and develop. So, the good news is, you're already capable of becoming more resilient.",
        subTitle2:"Cultivate Strong Relationships",
        text2:"Invest in your relationships with family and friends. Having a support system is crucial. It's these connections that provide you with emotional support when things get tough and also give you a sense of belonging and self-worth.",
        subTitle3:" Keep Things in Perspective",
        text3:"When you're in the thick of things, it's easy to lose perspective. Try to see beyond the present moment. Ask yourself: Will this matter in a year? Five years? This doesn't minimize your struggles but can help you focus on the bigger picture.",
        subTitle4:"Accept That Change is Part of Life",
        text4:"Change is inevitable, and sometimes it's beyond our control. Accepting that fact can help you focus on what you can change. It's about finding your agency and acting where you can make a difference.",
        subTitle5:"Take Care of Yourself",
        text5:"Self-care is vital. Pay attention to your own needs and feelings. Engage in activities that you enjoy and find relaxing. This includes taking care of your physical health—eating well, exercising, and getting enough sleep.",
        subTitle6:"Move Towards Your Goals",
        text6:"Set realistic and achievable goals. Even small accomplishments can boost your confidence and move you closer to what you want to achieve. Remember, it's about taking small steps consistently.",
        subTitle7:"Nurture a Positive View of Yourself",
        text7:"Develop confidence in your ability to solve problems. Trust your instincts. The way you view yourself can greatly influence how resilient you feel.",
        subTitle8:"Don't Be Afraid to Ask for Help",
        text8:"Sometimes, the strongest thing you can do is ask for help. If you're struggling, don't hesitate to seek support, whether from friends, family, or a professional.",
        subTitle9:"Practice Mindfulness",
        text9:"Mindfulness and meditation can enhance your response to stress. It's about being present in the moment and not overly reactive or overwhelmed by what's going on around you.",
        text10:"Remember, building resilience is a journey, not a destination. It's about taking steps every day, no matter how small, towards becoming a stronger, more adaptable you. "
    },

    {
        id: 3,
        article1: 3,
        title:"HOW TO STOP BEING LAZY",
        img: "/images/image1.png",
        name:"",
        date:"Last Updated Dec. 26, 2023",
        text0:"Tackling laziness can feel like a big challenge, Breaking it down, and tackling it step by step will make sure you overcome that bad habit.",
        subTitle1:"Break It Down",
        text1:"Big tasks can feel overwhelming, right? Break them into smaller, more manageable tasks. When you accomplish these mini-goals, it's not only satisfying but also boosts your motivation to tackle the next one.",
        subTitle2:"Set Realistic Goals",
        text2:"It's important to set achievable goals. If your goals are too lofty, it's easy to feel discouraged. Start small, and as you find your rhythm, you can gradually aim higher.",
        subTitle4:"Find Your 'Why'",
        text4:"Understanding why a task is important can be a powerful motivator. Whether it's for personal growth, health, or career advancement, keep your 'why' in mind.",
        subTitle5:"Celebrate Small Wins",
        text5:"Every time you complete a task, give yourself some credit. Celebrate these wins, no matter how small. This positive reinforcement can do wonders for your motivation.",
        subTitle6:"Take Care of Yourself",
        text6:"Never underestimate the power of a good night's sleep, healthy eating, and some exercise. When you feel good physically, it's easier to tackle mental or emotional challenges.",
        subTitle7:"Stay Inspired",
        text7:"Find books, podcasts, or even inspirational quotes that motivate you. Surrounding yourself with positive influences can spark that drive within you.",
        subTitle8:"Learn to Forgive Yourself",
        text8:"Finally, be kind to yourself. If you have an off day, it's okay. Don't beat yourself up. Acknowledge it, learn from it, and move forward.",
        text10:"Remember, overcoming laziness is a journey, and it's perfectly fine to take it one step at a time.",
    },
    {
        id: 4,
        article1: 4,
        title:"THE IMPORTANCE OF EATING HEALTHY",
        img: "/images/image9.png",
        name:"",
        date:"Last Updated Dec. 25, 2023",
        text0:"Eating healthy is not about perfection; it's about making better choices one meal at a time.",
        subTitle1:"Understand What 'Eating Healthy' Means",
        text1:"First, let's clarify what healthy eating is all about. It's not just about losing weight or cutting out certain foods. It's about nourishing your body, feeling great, and boosting your overall health. It's a balance of proteins, carbohydrates, fats, vitamins, and minerals.",
        subTitle2:"Start Small",
        text2:"You don't have to overhaul your diet overnight. Small, sustainable changes are the way to go. Maybe swap out that soda for water, choose whole grains instead of refined ones, or grab a piece of fruit instead of a sugary snack.",
        subTitle3:"Plan Your Meals",
        text3:"Planning is a game-changer. When you plan your meals, you're less likely to grab something unhealthy on the go. Start by planning a few meals a week and gradually increase it.",
        subTitle4:"Enjoying Your Food",
        text4:"Healthy eating isn't about restrictions; it's about enjoying a wide variety of foods that nourish your body. Take time to savor your food and appreciate its ability to fuel your body.",
        subTitle5:"Stay Hydrated",
        text5:"Drinking enough water is a crucial part of healthy eating. Sometimes, we mistake thirst for hunger. Before you reach for a snack, try having a glass of water first.",
        subTitle6:"Cook More at Home",
        text6:"Cooking at home gives you control over what you're eating. It's also a great way to experiment with new healthy recipes. Don't worry if you're not a master chef; there are tons of simple and quick healthy recipes out there.",
        subTitle7:"Don't Skip Meals",
        text7:"Skipping meals can lead to overeating later. Try to eat at regular intervals to keep your energy levels stable.",
        subTitle8:"Enjoying Your Food",
        text8:"Healthy eating isn't about restrictions; it's about enjoying a wide variety of foods that nourish your body. Take time to savor your food and appreciate its ability to fuel your body.",
        text10:"Remember, the goal of healthy eating is to feel good, have more energy, and improve your health. It's a personal journey, and it's all about finding what works for you."
    },
    
    { 
        id: 5,
        article3: 5,
        title:"LIFE LESSONS FOR TEENAGERS",
        img: "/images/image2.png",
        name:"",
        date:"Dec 22, 2023",
        text0:"",
        subTitle1:"Embrace Your Uniqueness",
        text1:"You're one of a kind, and that's your superpower. Never feel like you have to change to fit in. Embracing your uniqueness isn't always easy, but it's what makes you, well, you!",
        subTitle2:"It's Okay to Make Mistakes",
        text2:"Mistakes are part of growing up. They're not just errors; they're stepping stones to learning and getting better. So, when you mess up, don't be too hard on yourself. Reflect, learn, and move forward.",
        subTitle3:"Relationships Matter",
        text3:"The friends you make during your teenage years can be some of the most meaningful ones in your life. Cherish these relationships, but also know it's okay if some friendships naturally fade. People grow and change, and that's perfectly normal.",
        subTitle4:"Take Care of Your Health",
        text4:"Physical, mental, and emotional health are all equally important. Eat well, stay active, and find healthy ways to cope with stress. And it's okay to ask for help if you're struggling.",
        subTitle5:"The Internet is Forever",
        text5:"Be mindful of what you share online. Once something is out there, it's hard to take back. Think twice before posting that photo or comment.",
        subTitle6:"Dream Big, But Be Prepared to Work Hard",
        text6:"It's great to have big dreams, but remember that achieving them takes hard work, dedication, and sometimes, a bit of patience.",
        subTitle7:"Enjoy the Journey",
        text7:"Lastly, don't be in a rush to grow up. Enjoy being a teenager. Have fun, explore, and cherish these years. They go by faster than you think.",
        text10:"",

    },
    { 
        id: 6,
        article4: 6,
        title:"WHY YOU SHOULD NEVER QUIT",
        img: "/images/image10.png",
        name:"",
        date:"Dec 26, 2023",
        text0:"",
        subTitle1:"Growth Happens Outside Your Comfort Zone",
        text1:"You know, the moments when you feel like quitting are often the times you're growing the most. It's outside your comfort zone where the magic happens. Each challenge you face and work through adds to your strength, skills, and character. Think about how far you've come already that's all you, and that's amazing.",
        subTitle2:"Every Effort Counts",
        text2:"Every step you take, no matter how small, is progress. Even when it doesn't feel like it, you're moving forward. The effort you're putting in now is building something important, even if you can't see the results just yet. Remember, the most impressive skyscrapers were built brick by brick, day by day.",
        subTitle3:"Success Often Comes After the Toughest Trials",
        text3:"Have you ever heard stories about people who achieved incredible things? More often than not, they faced moments just like this, where everything seemed impossible. But they kept going, and that's why they succeeded. You're writing your own success story right now, and this chapter is an important one.",
        subTitle4:"You Have a Unique Value to Offer",
        text4:"There's only one you in this world, and you have something special to offer that nobody else can. Your perspective, your skills, your experiences – they're unique to you. When you quit, the world misses out on that. Believe in the value you bring to the table.",
        subTitle5:"Regret is Harder to Live With Than Challenges",
        text5:"Look, life's full of challenges, and they can be tough. But regret – that's tougher. It's the 'what ifs' and 'if only' that stick around way longer than the temporary struggle of pushing through. Imagine looking back and knowing you gave it your all. That's a feeling worth fighting for.",
        text10:"I know it's not easy, and it's okay to feel overwhelmed at times. But remember, this struggle is part of your journey, and it's shaping you into an even more incredible person.",

    },
    { 
        id: 7,
        article5: 7,
        title:"HOW TO DEAL WITH FEAR",
        img: "/images/image3.png",
        name:"",
        date:"Dec 26, 2023",
        text0:"",
        subTitle1:"Fear Often Comes from the Unknown",
        text1:"One of the biggest reasons fear feels so powerful is because it's tied to the unknown. It's like standing at the edge of a dark room; the darkness itself isn't scary, it's not knowing what's inside that gets to us. But think about this: once you turn on the light, the fear usually vanishes. The unknown becomes known, and the illusion of fear dissipates.",
        subTitle2:"Our Mind Amplifies Fear",
        text2:"Our minds are incredibly powerful. They have the ability to take a small worry and turn it into a mountain of fear. Often, what we fear is not as bad as the scenarios we create in our minds. It's like watching a scary movie and then being afraid of the dark the fear is created by the mind, not by the darkness itself.",
        subTitle3:"Fear is Often Based on Past Experiences",
        text3:"A lot of our fears are based on past experiences. But here's the thing just because something happened in the past, doesn't mean it'll happen again. Holding onto past fears is like wearing old glasses that don't fit anymore. They distort your view and keep you from seeing the present clearly.",
        subTitle4:"Fear Can Be a Product of Social Conditioning",
        text4:"We're often taught to fear certain things, sometimes without good reason. It's like being afraid of a spider because you saw someone else scream at the sight of one. When you really think about it, is the spider itself scary, or is it the reaction to the spider that's been ingrained in you?",
        subTitle5:"Overcoming Fear is Often About Perception",
        text5:"Changing your perception can change your experience of fear. It's like riding a roller coaster; some people are terrified, while others are thrilled. The ride is the same, but the way people perceive it is different. When you start to see fear as a challenge or an opportunity for growth, its power over you lessens.",
        subTitle6:"Fear Loses Its Power When Confronted",
        text6:"Finally, the most powerful way to prove that fear is an illusion is to confront it. It's like facing the monster under your bed and finding out it was just a pile of clothes. Each time you confront a fear, you take away its power, revealing it for the illusion it often is.",
        text10:"Remember, While fear can feel very real, it's often not as solid as it seems. It's a combination of the unknown, our perceptions, and our past experiences. By understanding this, you can start to take control of your fears, rather than letting them control you. ",
        
    },
    // { 
    //     id: 8,
    //     article6: 8,
    //     title:"THE ONLY PATH FORWARD",
    //     img: "/images/image5.jpg",
    //     name:"Billy",
    //     date:"Dec 2, 2022",
    // }
]

}  
